// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const EditorName = {
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Code: "code",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Code_desktop: "code-desktop",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Intellij: "intellij",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Goland: "goland",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Phpstorm: "phpstorm",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Pycharm: "pycharm",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Rubymine: "rubymine",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Webstorm: "webstorm",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Rider: "rider",
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Clion: "clion",
} as const;

export type EditorName = (typeof EditorName)[keyof typeof EditorName];

export const EditorVersion = {
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    Latest: "latest",
    /**
     * Standard workspace class - up to 4 cores, up to 8GB RAM, 30GB storage
     */
    Stable: "stable",
} as const;

export type EditorVersion = (typeof EditorVersion)[keyof typeof EditorVersion];

export const WorkspaceClass = {
    /**
     * Large workspace class - up to 8 cores, up to 16GB RAM, 50GB storage.
     */
    G1_large: "g1-large",
    /**
     * Standard workspace class - up to 4 cores, up to 8GB RAM, 30GB storage
     */
    G1_standard: "g1-standard",
} as const;

export type WorkspaceClass = (typeof WorkspaceClass)[keyof typeof WorkspaceClass];
