// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("gitpod");

/**
 * Your Gitpod access token. You can create these in your user settings: https://gitpod.io/user/tokens
 */
export declare const accessToken: string;
Object.defineProperty(exports, "accessToken", {
    get() {
        return __config.get("accessToken") ?? (utilities.getEnv("GITPOD_ACCESSTOKEN") || "");
    },
    enumerable: true,
});

/**
 * Id of the organisation who is going to own the workspaces. You can find this on the organisation settings page of the currently selected organisation: https://gitpod.io/settings
 */
export declare const organizationId: string;
Object.defineProperty(exports, "organizationId", {
    get() {
        return __config.get("organizationId") ?? (utilities.getEnv("GITPOD_ORGANISATIONID") || "");
    },
    enumerable: true,
});

/**
 * Id of owner account. This can be found on your user account page: https://gitpod.io/user/account
 */
export declare const ownerId: string;
Object.defineProperty(exports, "ownerId", {
    get() {
        return __config.get("ownerId") ?? (utilities.getEnv("GITPOD_OWNERID") || "");
    },
    enumerable: true,
});

