// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("gitpod");

/**
 * Your Gitpod access token
 */
export declare const accessToken: string;
Object.defineProperty(exports, "accessToken", {
    get() {
        return __config.get("accessToken") ?? (utilities.getEnv("GITPOD_ACCESSTOKEN") || "");
    },
    enumerable: true,
});

export declare const organizationId: string;
Object.defineProperty(exports, "organizationId", {
    get() {
        return __config.get("organizationId") ?? (utilities.getEnv("GITPOD_ORGANISATIONID") || "");
    },
    enumerable: true,
});

/**
 * Id of owner account
 */
export declare const ownerId: string;
Object.defineProperty(exports, "ownerId", {
    get() {
        return __config.get("ownerId") ?? (utilities.getEnv("GITPOD_OWNERID") || "");
    },
    enumerable: true,
});

