// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gitpod.Outputs
{

    [OutputType]
    public sealed class WorkspaceStateSpec
    {
        public readonly string Class;
        /// <summary>
        /// The IDE that has been chosen
        /// </summary>
        public readonly Outputs.WorkspaceStateSpecEditor Editor;

        [OutputConstructor]
        private WorkspaceStateSpec(
            string @class,

            Outputs.WorkspaceStateSpecEditor editor)
        {
            Class = @class;
            Editor = editor;
        }
    }
}
