// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Gitpod.Outputs
{

    [OutputType]
    public sealed class WorkspaceStateSpecEditor
    {
        /// <summary>
        /// Name of IDE that is being used in the workspace
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Version of the IDE that is being used in the workspace
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private WorkspaceStateSpecEditor(
            string name,

            string version)
        {
            Name = name;
            Version = version;
        }
    }
}
