// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Gitpod.Outputs
{

    [OutputType]
    public sealed class WorkspaceStateGitInfo
    {
        /// <summary>
        /// Git branch used to create the workspace
        /// </summary>
        public readonly string Branch;
        /// <summary>
        /// The git clone url used to create the workspace
        /// </summary>
        public readonly string CloneUrl;
        /// <summary>
        /// The commit hash used to create the workspace
        /// </summary>
        public readonly string LatestCommit;

        [OutputConstructor]
        private WorkspaceStateGitInfo(
            string branch,

            string cloneUrl,

            string latestCommit)
        {
            Branch = branch;
            CloneUrl = cloneUrl;
            LatestCommit = latestCommit;
        }
    }
}
