// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gitpod.Outputs
{

    [OutputType]
    public sealed class WorkspaceStateMetaData
    {
        public readonly string InstanceId;
        /// <summary>
        /// The name of the workspace
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the organization that the workspace belongs to
        /// </summary>
        public readonly string OrganizationId;
        /// <summary>
        /// The original context URL of the workspace
        /// </summary>
        public readonly string OriginalContextUrl;
        /// <summary>
        /// The ID of the user that owns the workspace
        /// </summary>
        public readonly string OwnerId;

        [OutputConstructor]
        private WorkspaceStateMetaData(
            string instanceId,

            string name,

            string organizationId,

            string originalContextUrl,

            string ownerId)
        {
            InstanceId = instanceId;
            Name = name;
            OrganizationId = organizationId;
            OriginalContextUrl = originalContextUrl;
            OwnerId = ownerId;
        }
    }
}
