// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import * as utilities from "../utilities";

export interface WorkspaceEditorArgs {
    /**
     * Name of the editor that you'd like to use in your Gitpod workspace. Defaults to VS Code desktop.
     */
    name?: pulumi.Input<enums.EditorName>;
    /**
     * Version of editor to use. Options are `latest` or `stable`. Defaults to `stable`
     */
    version?: pulumi.Input<enums.EditorVersion>;
}
/**
 * workspaceEditorArgsProvideDefaults sets the appropriate defaults for WorkspaceEditorArgs
 */
export function workspaceEditorArgsProvideDefaults(val: WorkspaceEditorArgs): WorkspaceEditorArgs {
    return {
        ...val,
        name: (val.name) ?? "code",
        version: (val.version) ?? "stable",
    };
}

