// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export function getWorkspace(args?: GetWorkspaceArgs, opts?: pulumi.InvokeOptions): Promise<GetWorkspaceResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitpod:index:getWorkspace", {
    }, opts);
}

export interface GetWorkspaceArgs {
}

export interface GetWorkspaceResult {
    /**
     * The information from git used to build the workspace
     */
    readonly gitInfo: outputs.WorkspaceStateGitInfo;
    /**
     * The metadata of the workspace
     */
    readonly metadata: outputs.WorkspaceStateMetaData;
    readonly spec: outputs.WorkspaceStateSpec;
    /**
     * The ID of the workspace
     */
    readonly workspaceId: string;
}
export function getWorkspaceOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetWorkspaceResult> {
    return pulumi.output(getWorkspace(opts))
}
